db:
  host: 127.0.0.1
  port: 5432
  user: dns-bh
  name: dns-bh
  password: Secr3t
  ssl: false

smtp:
  host: 127.0.0.1
  port: 587
  user: auth_user
  password: auth_secret
  sender: dns-bh@example.net
  recipient: admin@example.net
